version: '3.8'

services:
  tour-app:
    build: .
    container_name: tour-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/tourdb
      - DATABASE_USERNAME=touruser
      - DATABASE_PASSWORD=tourpass
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - tour-network
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: tour-postgres
    environment:
      - POSTGRES_DB=tourdb
      - POSTGRES_USER=touruser
      - POSTGRES_PASSWORD=tourpass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tour-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U touruser -d tourdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tour-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tourapp.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - tour-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  tour-network:
    driver: bridge